BYBIT_API_KEY = 'PUT YOUR API KEY HERE'
BYBIT_API_SECRET = 'PUT YOUR API SECRET HERE'
TELEGRAM_BOT_TOKEN = 'PUT YOUR BOT TOKEN HERE'
TELEGRAM_CHANNEL_ID = 'PUT YOUR TELEGRAM CHANNEL ID HERE' # Используем ID канала из Веб-версии. 
CHECK_INTERVAL = 300 # Интервал проверки в секундах
PRICE_CHANGE_THRESHOLD = 10  # Порог изменения цены в процентах
