BYBIT_API_KEY = 'PUT YOUR API KEY HERE'
BYBIT_API_SECRET = 'PUT YOUR API SECRET HERE'
TELEGRAM_BOT_TOKEN = 'PUT YOUR BOT TOKEN HERE'
TELEGRAM_CHAT_ID = 'PUT YOUR TELEGRAM CHAT ID HERE'
CHECK_INTERVAL = 5 # Интервал проверки в секундах
PRICE_CHANGE_THRESHOLD = 10  # Порог изменения цены в процентах